version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./visualizer_fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
